# 匹配
registration_method: NDTMANUAL   # 选择点云匹配方法，目前支持：NDT ICP NDTMANUAL ICPMANUAL  


# 当前帧
# no_filter指不对点云滤波，在匹配中，理论上点云越稠密，精度越高，但是速度也越慢
# 所以提供这种不滤波的模式做为对比，以方便使用者去体会精度和效率随稠密度的变化关系
frame_filter: voxel_filter # 选择当前帧点云滤波方法，目前支持：voxel_filter、no_filter

# 局部地图
key_frame_distance: 2.0 # 关键帧距离
local_frame_num: 20
local_map_filter: voxel_filter # 选择滑窗地图点云滤波方法，目前支持：voxel_filter、no_filter


# 各配置选项对应参数
## 匹配相关参数
NDT:
    res : 1.0
    step_size : 0.1
    trans_eps : 0.01
    max_iter : 30

NDTMANUAL:
    res : 1.0
    step_size : 0.1
    trans_eps : 0.01
    max_iter : 30
    outlier_ratio : 0.55

ICP:
    euclid_eps : 0.01
    max_correspond_dis : 2
    trans_eps : 0.01
    max_iter : 30

ICPMANUAL:
    max_correspond_dis : 2
    max_iter : 30
    
## 滤波相关参数
## 格子越小，点越多，精度越高，但是速度越慢
voxel_filter:
    local_map:
        leaf_size: [0.3, 0.3, 0.3] #原来是0.6    0.4
    frame:
        leaf_size: [0.5, 0.5, 0.5] #原来是1.3    0.6